
import React, { useState } from 'react';
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search, Loader2, Copy, FileText } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useTenantContext } from '@/contexts/TenantContext';
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

interface MetricsSearchProps {
  className?: string;
}

const MetricsSearch: React.FC<MetricsSearchProps> = ({ className }) => {
  const [query, setQuery] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();
  const { selectedTenant } = useTenantContext();

  // Function to format numbers in the response
  const formatResponse = (response: string): string => {
    // Format numbers (Add commas to numbers over 1000)
    const withFormattedNumbers = response.replace(/\b(\d{4,})\b/g, (match) => {
      return parseInt(match).toLocaleString();
    });
    
    return withFormattedNumbers;
  };

  // Function to handle copying the response to clipboard
  const copyToClipboard = () => {
    if (!result) return;
    
    navigator.clipboard.writeText(result)
      .then(() => {
        toast({
          title: "Copied!",
          description: "Answer copied to clipboard",
        });
      })
      .catch(err => {
        toast({
          title: "Failed to copy",
          description: "Could not copy text to clipboard",
          variant: "destructive",
        });
      });
  };

  // Function to "export" the result (for now just copies with formatting)
  const exportResult = () => {
    if (!result) return;
    
    const formattedExport = `
Query: ${query}
Tenant: ${selectedTenant.name}
Date: ${new Date().toLocaleString()}
-----------------------------
${result}
-----------------------------
Generated by MLCyberLLM
    `.trim();
    
    navigator.clipboard.writeText(formattedExport)
      .then(() => {
        toast({
          title: "Exported!",
          description: "Formatted answer copied to clipboard",
        });
      })
      .catch(err => {
        toast({
          title: "Failed to export",
          description: "Could not copy formatted text to clipboard",
          variant: "destructive",
        });
      });
  };

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) {
      toast({
        title: "Empty Query",
        description: "Please enter a search query",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      // First try to use Supabase function if available
      try {
        const { data, error } = await supabase.functions.invoke('search-metrics', {
          body: { 
            query: query,
            tenantId: selectedTenant.id,
            tenantName: selectedTenant.name
          },
        });

        if (error) throw error;
        setResult(formatResponse(data.answer));
      } catch (supabaseError) {
        // If Supabase function fails, use mock response
        console.warn('Falling back to mock response:', supabaseError);
        
        // Generate a mock response based on the query
        const mockResponses: Record<string, string> = {
          'security': 'Your security posture score is 78/100. There are 3 critical vulnerabilities that need immediate attention.',
          'alerts': 'There have been 127 alerts in the last 24 hours, a 15% increase from yesterday.',
          'incidents': 'There are 8 active incidents. 2 new incidents were detected today.',
          'vulnerabilities': 'There are 280 open vulnerabilities across all systems. Critical: 23, High: 45, Medium: 78, Low: 134.',
          'compliance': 'Current compliance status: PCI DSS (92%), HIPAA (87%), ISO 27001 (94%), SOC 2 (89%).',
          'threats': 'Top threat vectors: Phishing (42%), Malware (28%), Credential theft (17%), Network intrusion (13%).',
          'status': 'Overall security status: WARNING. Network security requires immediate attention.'
        };

        // Find the most relevant mock response
        const queryLower = query.toLowerCase();
        let response = 'I don\'t have specific information about that query. Please try asking about security, alerts, incidents, vulnerabilities, compliance, or threats.';
        
        for (const [key, value] of Object.entries(mockResponses)) {
          if (queryLower.includes(key)) {
            response = value;
            break;
          }
        }
        
        // Apply formatting to the mock response
        const formattedResponse = formatResponse(response);
        
        // Simulate API delay
        setTimeout(() => {
          setResult(formattedResponse);
        }, 800);
      }
    } catch (error: any) {
      console.error('Error searching metrics:', error);
      toast({
        title: "Search Error",
        description: error.message || "Failed to search metrics",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  // Function to format the result with enhanced styling
  const renderFormattedResult = () => {
    if (!result) return null;

    // Detect and highlight numbers
    const formattedResult = result.split(/(\s+)/).map((word, index) => {
      // Check if the word is a number (with possible commas and decimal points)
      const isNumber = /^[\d,]+(\.\d+)?%?$/.test(word);
      // Check if it's a percentage
      const isPercentage = word.endsWith('%');
      // Check if it represents a critical value (containing words like critical, high, warning)
      const isCritical = /critical|high|warning/i.test(word);
      const isPositive = /good|secure|compliant|resolved/i.test(word);
      
      if (isNumber) {
        return (
          <Badge 
            key={index} 
            variant={isPercentage ? "outline" : "default"}
            className={`font-mono ${isPercentage ? 'bg-secondary/30' : 'bg-primary/20'} text-foreground`}
          >
            {word}
          </Badge>
        );
      } else if (isCritical) {
        return (
          <span key={index} className="text-destructive font-medium">
            {word}
          </span>
        );
      } else if (isPositive) {
        return (
          <span key={index} className="text-emerald-600 dark:text-emerald-400 font-medium">
            {word}
          </span>
        );
      }
      
      return <span key={index}>{word}</span>;
    });

    return (
      <Card className="mt-4 p-4 rounded-md">
        <div className="flex justify-between items-start mb-2">
          <h4 className="text-sm font-medium text-muted-foreground">Answer:</h4>
          <div className="flex gap-2">
            <Button variant="ghost" size="icon" onClick={copyToClipboard} title="Copy to clipboard">
              <Copy className="h-4 w-4" />
            </Button>
            <Button variant="ghost" size="icon" onClick={exportResult} title="Export formatted answer">
              <FileText className="h-4 w-4" />
            </Button>
          </div>
        </div>
        <Separator className="my-2" />
        <div className="whitespace-pre-wrap text-sm leading-relaxed mt-2 font-medium">
          {formattedResult}
        </div>
      </Card>
    );
  };

  return (
    <div className={`dashboard-card ${className}`}>
      <div className="dashboard-card-header">
        <h3 className="dashboard-card-title">Command Center</h3>
      </div>
      
      <div className="mt-2 space-y-4">
        <form onSubmit={handleSearch} className="flex gap-2">
          <Input
            placeholder="AI driven security intelligent insights"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="flex-1"
          />
          <Button type="submit" disabled={loading}>
            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
          </Button>
        </form>
        
        {result && renderFormattedResult()}
        
        {!result && !loading && (
          <div className="mt-4 p-3 rounded-md bg-muted/10 text-sm text-muted-foreground">
            <p>Try asking:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>What is our current security posture?</li>
              <li>How many critical vulnerabilities do we have?</li>
              <li>Show me recent security incidents</li>
              <li>What is our compliance status?</li>
            </ul>
          </div>
        )}
      </div>
    </div>
  );
};

export default MetricsSearch;
