// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwubbgxvpkpyaisxkwhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dWJiZ3h2cGtweWFpc3hrd2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTc1NTIsImV4cCI6MjA1Nzk5MzU1Mn0.i0nRk5nQrUZwXea5YAJseQfujPNSFStX2nQ8UXFNPwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);